logging:
  level: INFO

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=mySHOPPFStock
    username: sa
    password: 123456
    initialize: false

  data:
    rest:
      base-path: /api

  jpa:
    database: SQL_SERVER
    show-sql: true

  mvc:
    date-format: yyyy-MM-dd
    locale: zh_CN

  messages:
    basename: messages_zh_CN

security:
  enable-csrf: true

server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
