logging:
  level: ERROR

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://124.114.155.226:1433;databaseName=mySHOPPFStock
    username: sa
    password: sa
    initialize: false

  data:
    rest:
      base-path: /api

  jpa:
    database: SQL_SERVER
    show-sql: true

  mvc:
    date-format: yyyy-MM-dd
    locale: zh_CN

  messages:
    basename: messages_zh_CN
  mobile:
    devicedelegatingviewresolver:
      enabled: true

security:
  enable-csrf: true

server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

